version: '3'
services:
    frs:
        build: .
        restart: always
        ports:
          - 8000:8000
        depends_on:
          - redis_semaphore
          - redis_cache
        links:
          - redis_cache

    redis_semaphore:
        image: redis:7.2.3
        restart: always

    redis_cache:
        image: redis:7.2.3
        restart: always
