[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN001",
    "ANN101",
    "ANN201",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D203",
    "D212",
    "N802",
    "PT009",
    "S101",
    "S105",
]
