# Generated by Django 5.0.2 on 2024-03-01 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageFaceEncoding",
            fields=[
                (
                    "file_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceEncodingValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(127),
                        ],
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="face_encodings.imagefaceencoding",
                    ),
                ),
            ],
            options={
                "unique_together": {("index", "image")},
            },
        ),
    ]
