# Generated by Django 5.0.2 on 2024-03-01 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_encodings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AverageFaceEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_images_processed", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AverageFaceEncodingValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(127),
                        ],
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                (
                    "average_face_encoding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="face_encodings.averagefaceencoding",
                    ),
                ),
            ],
        ),
    ]
